export interface BankQuestion {
  id: string;
  paper: 'Paper 1' | 'Paper 2';
  paperTitle: string;
  section: 'Section A' | 'Section B';
  questionNumber: string;
  marks: number;
  questionText: string;
  topic: string;
  subTopic?: string;
}

export const questionBankData: BankQuestion[] = [
  // ==========================================
  // PAPER 1: SECTION A - Question 1 (4 Marks)
  // ==========================================
  {
    id: "p1-q1-1",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two sampling techniques.",
    topic: "Methods of Research",
    subTopic: "Types of Data, Methods and Research Design"
  },
  {
    id: "p1-q1-2",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two social values.",
    topic: "Socialisation and Identity",
    subTopic: "Socialisation and the Creation of Social Identity"
  },
  {
    id: "p1-q1-3",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two quantitative research methods.",
    topic: "Methods of Research",
    subTopic: "Types of Data, Methods and Research Design"
  },
  {
    id: "p1-q1-4",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two social characteristics associated with the elderly.",
    topic: "Socialisation and Identity",
    subTopic: "Age Identity"
  },
  {
    id: "p1-q1-5",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two characteristics of upper-class culture.",
    topic: "Socialisation and Identity",
    subTopic: "Social Class Identity"
  },
  {
    id: "p1-q1-6",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two informal social sanctions.",
    topic: "Social Control and Deviance",
    subTopic: "Social Control, Conformity and Resistance"
  },
  {
    id: "p1-q1-7",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two social roles associated with young people.",
    topic: "Socialisation and Identity",
    subTopic: "Youth Identity"
  },
  {
    id: "p1-q1-8",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two types of questionnaire.",
    topic: "Methods of Research",
    subTopic: "Types of Data, Methods and Research Design"
  },
  {
    id: "p1-q1-9",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two examples of social norms.",
    topic: "Socialisation and Identity",
    subTopic: "Socialisation and the Creation of Social Identity"
  },
  {
    id: "p1-q1-10",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two examples of social identities.",
    topic: "Socialisation and Identity",
    subTopic: "Social Identity and Change"
  },
  {
    id: "p1-q1-11",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two features of globalisation.",
    topic: "Socialisation and Identity",
    subTopic: "Social Identity and Change"
  },
  {
    id: "p1-q1-12",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two ways the peer group may influence behaviour.",
    topic: "Socialisation and Identity",
    subTopic: "Agents of Socialisation"
  },
  {
    id: "p1-q1-13",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two characteristics of youth identity.",
    topic: "Socialisation and Identity",
    subTopic: "Youth Identity"
  },
  {
    id: "p1-q1-14",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two features of longitudinal studies.",
    topic: "Methods of Research",
    subTopic: "Types of Data, Methods and Research Design"
  },
  {
    id: "p1-q1-15",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two negative social sanctions.",
    topic: "Social Control and Deviance",
    subTopic: "Social Control, Conformity and Resistance"
  },
  {
    id: "p1-q1-16",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two types of interview used in sociological research.",
    topic: "Methods of Research",
    subTopic: "Types of Data, Methods and Research Design"
  },
  {
    id: "p1-q1-17",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two types of observation used in sociological research.",
    topic: "Methods of Research",
    subTopic: "Types of Data, Methods and Research Design"
  },
  {
    id: "p1-q1-18",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two types of masculinity.",
    topic: "Socialisation and Identity",
    subTopic: "Gender Identity"
  },
  {
    id: "p1-q1-19",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two types of qualitative interview.",
    topic: "Methods of Research",
    subTopic: "Types of Data, Methods and Research Design"
  },
  {
    id: "p1-q1-20",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two features of a laboratory experiment.",
    topic: "Methods of Research",
    subTopic: "Types of Data, Methods and Research Design"
  },
  {
    id: "p1-q1-21",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two ways children learn about gender identity.",
    topic: "Socialisation and Identity",
    subTopic: "Gender Identity"
  },

  // =========================================================
  // PAPER 1: SECTION A - Question 2(a) & 2(b) (8 + 6 Marks)
  // =========================================================
  {
    id: "p1-q2-1",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two ethical issues linked to sociological research. [8]\n(b) Explain two limitations of using official statistics in sociological research. [6]",
    topic: "Methods of Research",
    subTopic: "Research Issues & Secondary Data"
  },
  {
    id: "p1-q2-2",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two ways an interviewer may influence answers when carrying out sociological interviews. [8]\n(b) Explain one strength and one limitation of using an overt approach to participant observation. [6]",
    topic: "Methods of Research",
    subTopic: "Interviews & Observational Research"
  },
  {
    id: "p1-q2-3",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two reasons why a researcher might use a non-representative sampling technique. [8]\n(b) Explain two strengths of group interviews as a research method. [6]",
    topic: "Methods of Research",
    subTopic: "Sampling & Group Interviews"
  },
  {
    id: "p1-q2-4",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two reasons why positivists favour the use of questionnaires. [8]\n(b) Explain two limitations of field experiments as a research method. [6]",
    topic: "Methods of Research",
    subTopic: "Positivism & Questionnaires vs Experiments"
  },
  {
    id: "p1-q2-5",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two characteristics of the interpretivist approach to sociological research. [8]\n(b) Explain two strengths of closed-ended questionnaires as a research method. [6]",
    topic: "Methods of Research",
    subTopic: "Interpretivism & Quantitative Questionnaires"
  },
  {
    id: "p1-q2-6",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two practical factors that can influence choice of research method. [8]\n(b) Explain two limitations of using an overt approach to participant observation. [6]",
    topic: "Methods of Research",
    subTopic: "Practical Factors & Participant Observation"
  },
  {
    id: "p1-q2-7",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two ethical issues associated with sociological research. [8]\n(b) Explain one strength and one limitation of official statistics. [6]",
    topic: "Methods of Research",
    subTopic: "Ethics & Secondary Official Statistics"
  },
  {
    id: "p1-q2-8",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two characteristics of the positivist approach to sociological research. [8]\n(b) Explain two strengths of structured interviews as a research method. [6]",
    topic: "Methods of Research",
    subTopic: "Positivism & Structured Interviews"
  },
  {
    id: "p1-q2-9",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two ways that research might be affected by how it is funded. [8]\n(b) Explain one strength and one limitation of using qualitative secondary data in sociological research. [6]",
    topic: "Methods of Research",
    subTopic: "Funding, Bias & Qualitative Secondary Data"
  },
  {
    id: "p1-q2-10",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two ways sociological research may be affected by bias. [8]\n(b) Explain one strength and one limitation of unstructured interviews as a research method. [6]",
    topic: "Methods of Research",
    subTopic: "Researcher Bias & Unstructured Interviews"
  },
  {
    id: "p1-q2-11",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two features of the interpretivist approach to research. [8]\n(b) Explain one strength and one limitation of questionnaires as a research method. [6]",
    topic: "Methods of Research",
    subTopic: "Interpretivism & Questionnaires"
  },
  {
    id: "p1-q2-12",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two problems a researcher may face in gaining access to a study group. [8]\n(b) Explain two limitations of longitudinal studies. [6]",
    topic: "Methods of Research",
    subTopic: "Gaining Access & Longitudinal Studies"
  },
  {
    id: "p1-q2-13",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two practical factors to consider when conducting observational studies. [8]\n(b) Explain one strength and one limitation of using content analysis as a research method. [6]",
    topic: "Methods of Research",
    subTopic: "Observations & Content Analysis"
  },
  {
    id: "p1-q2-14",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two reasons why a researcher might use a pilot study. [8]\n(b) Explain two strengths of questionnaires as a research method. [6]",
    topic: "Methods of Research",
    subTopic: "Pilot Studies & Questionnaires"
  },
  {
    id: "p1-q2-15",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two ways the values of the sociologist may lead to bias in research findings. [8]\n(b) Explain two strengths of using a covert approach to participant observation. [6]",
    topic: "Methods of Research",
    subTopic: "Values, Objectivity & Covert Observation"
  },
  {
    id: "p1-q2-16",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two reasons why interpretivists use participant observation in sociological research. [8]\n(b) Explain two strengths of using official statistics in sociological research. [6]",
    topic: "Methods of Research",
    subTopic: "Interpretivism, Observation & Statistics"
  },
  {
    id: "p1-q2-17",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two ways of achieving reliability in sociological research. [8]\n(b) Explain two limitations of using a covert approach to participant observation. [6]",
    topic: "Methods of Research",
    subTopic: "Reliability & Covert Observation Ethics"
  },
  {
    id: "p1-q2-18",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two reasons why it is difficult to be objective when conducting sociological research. [8]\n(b) Explain two limitations of group interviews as a research method. [6]",
    topic: "Methods of Research",
    subTopic: "Objectivity & Group Interviews"
  },
  {
    id: "p1-q2-19",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two reasons why positivists use experiments in sociological research. [8]\n(b) Explain two limitations of questionnaires as a research method. [6]",
    topic: "Methods of Research",
    subTopic: "Experiments & Questionnaires"
  },
  {
    id: "p1-q2-20",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two ethical factors to consider when conducting observational studies. [8]\n(b) Explain two strengths of using content analysis in sociological research. [6]",
    topic: "Methods of Research",
    subTopic: "Ethics in Observation & Content Analysis"
  },
  {
    id: "p1-q2-21",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two reasons why some social groups are difficult to study. [8]\n(b) Explain two strengths of online questionnaires. [6]",
    topic: "Methods of Research",
    subTopic: "Hard-to-reach Groups & Digital Methods"
  },
  {
    id: "p1-q2-22",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two reasons why unstructured interviews are high in validity. [8]\n(b) Explain two strengths of using laboratory experiments in sociological research. [6]",
    topic: "Methods of Research",
    subTopic: "Validity, Interviews & Lab Experiments"
  },

  // =========================================================
  // PAPER 1: SECTION A - Question 3(a) & 3(b) (10 + 6 Marks)
  // =========================================================
  {
    id: "p1-q3-1",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "‘Religion is the most important influence in shaping an individual's identity.’\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Socialisation and Identity",
    subTopic: "Religious & Cultural Identity"
  },
  {
    id: "p1-q3-2",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "‘The media is the most important influence in shaping youth identity.’\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Socialisation and Identity",
    subTopic: "Youth Identity & Media Socialisation"
  },
  {
    id: "p1-q3-3",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "‘Family is the most important influence on age identity.’\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Socialisation and Identity",
    subTopic: "Age Identity & Primary Socialisation"
  },
  {
    id: "p1-q3-4",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "‘Cultural deprivation is the main cause of deviant behaviour.’\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Social Control and Deviance",
    subTopic: "Theories of Deviance & Subcultures"
  },
  {
    id: "p1-q3-5",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "‘Education is the most important agent of socialisation in shaping identity.’\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Socialisation and Identity",
    subTopic: "Education & Secondary Socialisation"
  },
  {
    id: "p1-q3-6",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "‘Male identity is changing.’\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Socialisation and Identity",
    subTopic: "Gender Identity & Crisis of Masculinity"
  },
  {
    id: "p1-q3-7",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "‘Ethnic identity is changing, with new hybrid identities emerging.’\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Socialisation and Identity",
    subTopic: "Ethnic Identity & Hybridity"
  },
  {
    id: "p1-q3-8",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "‘The family is the most important influence on social class identity.’\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Socialisation and Identity",
    subTopic: "Social Class Identity & Cultural Capital"
  },
  {
    id: "p1-q3-9",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "‘The existence of subcultures best explains deviant behaviour.’\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Social Control and Deviance",
    subTopic: "Subcultural Theories of Deviance"
  },
  {
    id: "p1-q3-10",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "‘The family is the main influence on gender identity.’\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Socialisation and Identity",
    subTopic: "Gender Role Socialisation"
  },
  {
    id: "p1-q3-11",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "‘Under-socialisation is the main cause of deviance.’\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Social Control and Deviance",
    subTopic: "Functionalism, New Right & Inadequate Socialisation"
  },
  {
    id: "p1-q3-12",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "‘Religion is the most important factor shaping ethnic identity.’\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Socialisation and Identity",
    subTopic: "Ethnic & Religious Socialisation"
  },
  {
    id: "p1-q3-13",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "‘Under-socialisation is the main reason that individuals act in deviant ways.’\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Social Control and Deviance",
    subTopic: "Theories of Conformity & Deviance"
  },
  {
    id: "p1-q3-14",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "‘Family is the main influence on ethnic identity.’\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Socialisation and Identity",
    subTopic: "Ethnic Identity Socialisation"
  },
  {
    id: "p1-q3-15",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "‘Socialisation is a one-way process.’\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Socialisation and Identity",
    subTopic: "Structuralism vs Social Action (Active Agency)"
  },
  {
    id: "p1-q3-16",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "‘Marginalisation provides the best explanation for deviant behaviour.’\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Social Control and Deviance",
    subTopic: "Marginalisation, Relative Deprivation & Deviance"
  },
  {
    id: "p1-q3-17",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "‘Peer group is the most important influence on class identity.’\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Socialisation and Identity",
    subTopic: "Peer Groups & Social Class"
  },
  {
    id: "p1-q3-18",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "‘Subcultural norms and values cause people to act in deviant ways.’\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Social Control and Deviance",
    subTopic: "Subcultural Explanations of Crime and Deviance"
  },
  {
    id: "p1-q3-19",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "‘Education is the most important influence on an individual’s gender identity.’\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Socialisation and Identity",
    subTopic: "Gender Identity & Schooling"
  },
  {
    id: "p1-q3-20",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "‘Education is the most important influence in shaping class identity.’\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Socialisation and Identity",
    subTopic: "Education, Cultural Capital & Class"
  },
  {
    id: "p1-q3-21",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "‘The peer group is the most important influence in shaping age identity.’\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Socialisation and Identity",
    subTopic: "Age Identity & Youth Subcultures"
  },
  {
    id: "p1-q3-22",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "‘Inadequate socialisation is the main cause of deviant behaviour.’\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Social Control and Deviance",
    subTopic: "Social Control, Conformity and Deviance"
  },

  // =========================================================
  // PAPER 1: SECTION B - Essays (26 Marks)
  // =========================================================
  {
    id: "p1-secb-1",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the use of longitudinal studies in sociological research.",
    topic: "Methods of Research",
    subTopic: "Research Design & Longitudinal Studies"
  },
  {
    id: "p1-secb-2",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that sociologists exaggerate the extent to which human behaviour is shaped by socialisation.",
    topic: "Socialisation and Identity",
    subTopic: "Nature vs Nurture & Agency vs Structure"
  },
  {
    id: "p1-secb-3",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that traditional male identity has little influence on male behaviour today.",
    topic: "Socialisation and Identity",
    subTopic: "Changing Masculinities & Gender Identity"
  },
  {
    id: "p1-secb-4",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the arguments for using a covert approach to participant observation.",
    topic: "Methods of Research",
    subTopic: "Covert vs Overt Participant Observation"
  },
  {
    id: "p1-secb-5",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate sociological explanations of deviance.",
    topic: "Social Control and Deviance",
    subTopic: "Structural, Interactionist and Subcultural Explanations"
  },
  {
    id: "p1-secb-6",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that using different research methods together is more effective than using one method.",
    topic: "Methods of Research",
    subTopic: "Triangulation & Methodological Pluralism"
  },
  {
    id: "p1-secb-7",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that peers are the most important agent shaping an individual’s identity.",
    topic: "Socialisation and Identity",
    subTopic: "Agents of Socialisation"
  },
  {
    id: "p1-secb-8",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that scientific methods have no value in sociological research.",
    topic: "Methods of Research",
    subTopic: "Positivism vs Interpretivism & Scientific Method"
  },
  {
    id: "p1-secb-9",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that gender identity is changing.",
    topic: "Socialisation and Identity",
    subTopic: "Gender Identity & Social Change"
  },
  {
    id: "p1-secb-10",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that sociological research should be value free.",
    topic: "Methods of Research",
    subTopic: "Value Freedom, Objectivity and Ethics"
  },
  {
    id: "p1-secb-11",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate cultural explanations of deviance.",
    topic: "Social Control and Deviance",
    subTopic: "Cultural & Subcultural Explanations of Deviance"
  },
  {
    id: "p1-secb-12",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that quantitative research methods have more strengths than limitations.",
    topic: "Methods of Research",
    subTopic: "Quantitative vs Qualitative Methodologies"
  },
  {
    id: "p1-secb-13",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that human behaviour is shaped entirely by the process of socialisation.",
    topic: "Socialisation and Identity",
    subTopic: "Socialisation, Determinism and Human Agency"
  },
  {
    id: "p1-secb-14",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the use of qualitative interview methods in sociological research.",
    topic: "Methods of Research",
    subTopic: "Unstructured & Semi-Structured Interviews"
  },
  {
    id: "p1-secb-15",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that social identities are changing due to increased choice.",
    topic: "Socialisation and Identity",
    subTopic: "Postmodern Identity, Consumerism & Choice"
  },
  {
    id: "p1-secb-16",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that the strengths of overt participant observation outweigh the limitations.",
    topic: "Methods of Research",
    subTopic: "Overt Observation & Hawthorne Effect"
  },
  {
    id: "p1-secb-17",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that socialisation is the most significant factor in shaping human behaviour.",
    topic: "Socialisation and Identity",
    subTopic: "Socialisation vs Biology/Agency"
  },
  {
    id: "p1-secb-18",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that the research methods of the natural sciences should not be used in sociological research.",
    topic: "Methods of Research",
    subTopic: "Positivist Scientific Method vs Interpretivism"
  },
  {
    id: "p1-secb-19",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that age is the main influence on a person’s identity.",
    topic: "Socialisation and Identity",
    subTopic: "Age Identity & Life Course"
  },
  {
    id: "p1-secb-20",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the use of experiments in sociological research.",
    topic: "Methods of Research",
    subTopic: "Laboratory and Field Experiments"
  },
  {
    id: "p1-secb-21",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that the media is the most important influence in shaping gender identity.",
    topic: "Socialisation and Identity",
    subTopic: "Media Socialisation & Gender Representations"
  },
  {
    id: "p1-secb-22",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that practical factors are the main influence on a sociologist’s choice of research method.",
    topic: "Methods of Research",
    subTopic: "Practical, Theoretical and Ethical Factors"
  },
  {
    id: "p1-secb-23",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that social class has little influence on identity today.",
    topic: "Socialisation and Identity",
    subTopic: "Social Class Identity & Postmodern Claims"
  },
  {
    id: "p1-secb-24",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that qualitative interviews have little value in sociological research.",
    topic: "Methods of Research",
    subTopic: "Qualitative Interviews, Validity and Reliability"
  },
  {
    id: "p1-secb-25",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that society can be studied objectively.",
    topic: "Methods of Research",
    subTopic: "Objectivity, Values and Methodology"
  },
  {
    id: "p1-secb-26",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that age identities are no longer clear and fixed.",
    topic: "Socialisation and Identity",
    subTopic: "Age Identity & Postmodern Fragmentation"
  },
  {
    id: "p1-secb-27",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that nature is more important than nurture in shaping human behaviour.",
    topic: "Socialisation and Identity",
    subTopic: "Nature vs Nurture Debate"
  },
  {
    id: "p1-secb-28",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that qualitative methods are unsuitable for sociological research because they lack reliability.",
    topic: "Methods of Research",
    subTopic: "Qualitative Methods & Reliability vs Validity"
  },
  {
    id: "p1-secb-29",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that social class is no longer an important influence on a person’s identity.",
    topic: "Socialisation and Identity",
    subTopic: "Social Class Identity in Contemporary Society"
  },
  {
    id: "p1-secb-30",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that sociologists should use a scientific approach to research.",
    topic: "Methods of Research",
    subTopic: "Positivism & Scientific Sociology"
  },
  {
    id: "p1-secb-31",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that changes in gender identity have been exaggerated.",
    topic: "Socialisation and Identity",
    subTopic: "Gender Identity Continuity vs Change"
  },
  {
    id: "p1-secb-32",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that qualitative interviews are a better method than questionnaires for studying society.",
    topic: "Methods of Research",
    subTopic: "Interviews vs Questionnaires"
  },
  {
    id: "p1-secb-33",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that ethnicity has little influence on identity today.",
    topic: "Socialisation and Identity",
    subTopic: "Ethnic Identity & Globalisation"
  },
  {
    id: "p1-secb-34",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that practical factors are the most important influence on choice of research method.",
    topic: "Methods of Research",
    subTopic: "Factors Influencing Methodological Choices"
  },
  {
    id: "p1-secb-35",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that age identities have changed over time.",
    topic: "Socialisation and Identity",
    subTopic: "Age Identity & Social Construction"
  },
  {
    id: "p1-secb-36",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that questionnaires have limited value in sociological research because they lack validity.",
    topic: "Methods of Research",
    subTopic: "Questionnaires & Construct Validity"
  },
  {
    id: "p1-secb-37",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that class is the main influence on social identity.",
    topic: "Socialisation and Identity",
    subTopic: "Social Class Identity & Economic Stratification"
  },
  {
    id: "p1-secb-38",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that qualitative interview methods provide the best way to study social behaviour.",
    topic: "Methods of Research",
    subTopic: "Qualitative Interviews & Verstehen"
  },
  {
    id: "p1-secb-39",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that human behaviour is shaped by nurture rather than nature.",
    topic: "Socialisation and Identity",
    subTopic: "Nature vs Nurture & Primary Socialisation"
  },
  {
    id: "p1-secb-40",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the positivist view that sociologists should use a scientific approach to research.",
    topic: "Methods of Research",
    subTopic: "Positivism, Empiricism & Scientific Rigour"
  },
  {
    id: "p1-secb-41",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that female identity is very different from fifty years ago.",
    topic: "Socialisation and Identity",
    subTopic: "Changing Female Identities & Feminism"
  },
  {
    id: "p1-secb-42",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the use of structured interviews in sociological research.",
    topic: "Methods of Research",
    subTopic: "Structured Interviews, Standardisation and Limitations"
  },
  {
    id: "p1-secb-43",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that the family is the most important agent of socialisation in shaping identity.",
    topic: "Socialisation and Identity",
    subTopic: "Primary Socialisation vs Secondary Agents"
  },
  {
    id: "p1-secb-44",
    paper: "Paper 1",
    paperTitle: "Paper 1: Socialisation, Identity and Methods of Research",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that sociological research can be value-free.",
    topic: "Methods of Research",
    subTopic: "Value Freedom & Objectivity"
  },

  // ==========================================
  // PAPER 2: SECTION A - Question 1 (4 Marks)
  // ==========================================
  {
    id: "p2-q1-1",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two social policies that restrict the behaviour of children. [4]",
    topic: "Childhood and Age",
    subTopic: "Social Policy & Childhood Regulation"
  },
  {
    id: "p2-q1-2",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two reasons for the decline in the number of marriages in some societies. [4]",
    topic: "Family Diversity & Social Change",
    subTopic: "Marriage & Divorce Trends"
  },
  {
    id: "p2-q1-3",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two ways increased life expectancy has impacted on the family. [4]",
    topic: "Family Diversity & Social Change",
    subTopic: "Demographic Trends & Ageing Population"
  },
  {
    id: "p2-q1-4",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two ways the state may influence the family. [4]",
    topic: "Family Diversity & Social Change",
    subTopic: "Social Policy & State Intervention"
  },
  {
    id: "p2-q1-5",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two ways grandparents may provide benefits for the family. [4]",
    topic: "Childhood and Age",
    subTopic: "Age & Beanpole Families"
  },
  {
    id: "p2-q1-6",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two ways motherhood has changed. [4]",
    topic: "Gender Roles and Relationships",
    subTopic: "Motherhood & Female Employment"
  },
  {
    id: "p2-q1-7",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two ways the increase of women in paid employment has affected the family. [4]",
    topic: "Gender Roles and Relationships",
    subTopic: "Dual-Earner Families & Conjugal Roles"
  },
  {
    id: "p2-q1-8",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two functions performed by the family. [4]",
    topic: "Theories of the Family",
    subTopic: "Functionalist Functions of the Family"
  },
  {
    id: "p2-q1-9",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two features of a nuclear family. [4]",
    topic: "Theories of the Family",
    subTopic: "Nuclear Family Structure"
  },
  {
    id: "p2-q1-10",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two ways children are protected from adult life. [4]",
    topic: "Childhood and Age",
    subTopic: "Social Construction of Childhood"
  },
  {
    id: "p2-q1-11",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two reasons women are now marrying at a later age. [4]",
    topic: "Family Diversity & Social Change",
    subTopic: "Demographic Trends & Marriage"
  },
  {
    id: "p2-q1-12",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two reasons people may stay in an unhappy marriage. [4]",
    topic: "Family Diversity & Social Change",
    subTopic: "Empty-Shell Marriages & Divorce Barriers"
  },
  {
    id: "p2-q1-13",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two ways the family can benefit its members. [4]",
    topic: "Theories of the Family",
    subTopic: "Functionalist & Psychological Benefits"
  },
  {
    id: "p2-q1-14",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two ways fatherhood is different today than in the past. [4]",
    topic: "Gender Roles and Relationships",
    subTopic: "New Fatherhood & Changing Conjugal Roles"
  },
  {
    id: "p2-q1-15",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two ways the family has become child-centred. [4]",
    topic: "Childhood and Age",
    subTopic: "Child-Centred Family"
  },
  {
    id: "p2-q1-16",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two ways social policies have had a positive impact on the family. [4]",
    topic: "Family Diversity & Social Change",
    subTopic: "Social Policy & Welfare"
  },
  {
    id: "p2-q1-17",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two ways social class can influence the experience of childhood in the family. [4]",
    topic: "Childhood and Age",
    subTopic: "Social Class & Childhood Experiences"
  },
  {
    id: "p2-q1-18",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two ways increased life expectancy may impact upon the family. [4]",
    topic: "Family Diversity & Social Change",
    subTopic: "Ageing Population & Extended Ties"
  },
  {
    id: "p2-q1-19",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two ways social policies may impact upon the family. [4]",
    topic: "Family Diversity & Social Change",
    subTopic: "State Regulation & Social Policy"
  },
  {
    id: "p2-q1-20",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 1",
    marks: 4,
    questionText: "Describe two ways childhood is a distinct period from adulthood. [4]",
    topic: "Childhood and Age",
    subTopic: "Childhood as a Social Construct"
  },

  // =========================================================
  // PAPER 2: SECTION A - Question 2(a) & 2(b) (8 + 6 Marks)
  // =========================================================
  {
    id: "p2-q2-1",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two ways in which the family benefits society, according to functionalists. [8]\n(b) Explain two limitations of the functionalist view of the family. [6]",
    topic: "Theories of the Family",
    subTopic: "Functionalist Perspective & Critiques"
  },
  {
    id: "p2-q2-2",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two ways the family supports ruling class interests, according to Marxist theory. [8]\n(b) Explain one strength and one limitation of the Marxist view of the family. [6]",
    topic: "Theories of the Family",
    subTopic: "Marxist Perspectives on the Family"
  },
  {
    id: "p2-q2-3",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two reasons why there may be greater gender equality within the family today than in the past. [8]\n(b) Explain one strength and one limitation of the liberal feminist view of the family. [6]",
    topic: "Gender Roles and Relationships",
    subTopic: "Gender Equality & Liberal Feminism"
  },
  {
    id: "p2-q2-4",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two ways the family supports the interests of men, according to feminists. [8]\n(b) Explain two limitations of radical feminist views of the family. [6]",
    topic: "Theories of the Family",
    subTopic: "Radical Feminism & Patriarchy"
  },
  {
    id: "p2-q2-5",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two ways that girls experience family life differently to boys, according to feminists. [8]\n(b) Explain two strengths of radical feminist views of the family. [6]",
    topic: "Gender Roles and Relationships",
    subTopic: "Gendered Socialisation & Radical Feminism"
  },
  {
    id: "p2-q2-6",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two ways the role of women in the family supports capitalism. [8]\n(b) Explain two limitations of Marxist feminist views of the family. [6]",
    topic: "Theories of the Family",
    subTopic: "Marxist Feminism & Capitalism"
  },
  {
    id: "p2-q2-7",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two ways the family supports the economy. [8]\n(b) Explain two strengths of Marxist views of the family. [6]",
    topic: "Theories of the Family",
    subTopic: "Economic Functions & Marxist Theory"
  },
  {
    id: "p2-q2-8",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two reasons for an increase in the age of first marriage. [8]\n(b) Explain one strength and one limitation of postmodernist views on family diversity. [6]",
    topic: "Family Diversity & Social Change",
    subTopic: "Postmodernism & Changing Marriage Trends"
  },
  {
    id: "p2-q2-9",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two ways social policies may influence family life. [8]\n(b) Explain one strength and one limitation of New Right views of the family. [6]",
    topic: "Family Diversity & Social Change",
    subTopic: "Social Policy & New Right Perspectives"
  },
  {
    id: "p2-q2-10",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two ways family life can be harmful for some members. [8]\n(b) Explain one strength and one limitation of radical feminist views of the family. [6]",
    topic: "Theories of the Family",
    subTopic: "Dark Side of the Family & Radical Feminism"
  },
  {
    id: "p2-q2-11",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two ways capitalism benefits from the role of women in the family. [8]\n(b) Explain two strengths of Marxist feminist views of the family. [6]",
    topic: "Theories of the Family",
    subTopic: "Marxist Feminism & Reserve Army of Labour"
  },
  {
    id: "p2-q2-12",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two ways the family prepares children for the workplace. [8]\n(b) Explain two limitations of Marxist views of the family. [6]",
    topic: "Theories of the Family",
    subTopic: "Socialisation into Workplace Hierarchy"
  },
  {
    id: "p2-q2-13",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two reasons for the increase in cohabitation in some societies. [8]\n(b) Explain two limitations of postmodernist views of family diversity. [6]",
    topic: "Family Diversity & Social Change",
    subTopic: "Cohabitation & Postmodern Diversity"
  },
  {
    id: "p2-q2-14",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two ways the family functions to benefit society. [8]\n(b) Explain two limitations of functionalist views of the family. [6]",
    topic: "Theories of the Family",
    subTopic: "Functionalist Perspective & Murdock/Parsons"
  },
  {
    id: "p2-q2-15",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two ways men benefit more than women from family life. [8]\n(b) Explain two limitations of radical feminist views of the family. [6]",
    topic: "Gender Roles and Relationships",
    subTopic: "Patriarchy & Division of Labour"
  },
  {
    id: "p2-q2-16",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two reasons fewer people are marrying today. [8]\n(b) Explain two strengths of New Right views of the family. [6]",
    topic: "Family Diversity & Social Change",
    subTopic: "Marriage Trends & New Right Critiques"
  },
  {
    id: "p2-q2-17",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two ways the family supports capitalism. [8]\n(b) Explain two strengths of Marxist views of the family. [6]",
    topic: "Theories of the Family",
    subTopic: "Marxism, Private Property & Ideology"
  },
  {
    id: "p2-q2-18",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two reasons for greater gender equality in some families. [8]\n(b) Explain one strength and one limitation of liberal feminist views of the family. [6]",
    topic: "Gender Roles and Relationships",
    subTopic: "March of Progress & Liberal Feminism"
  },
  {
    id: "p2-q2-19",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two reasons why fewer people are getting married. [8]\n(b) Explain one strength and one limitation of postmodernist views on family diversity. [6]",
    topic: "Family Diversity & Social Change",
    subTopic: "Secularisation, Individualisation & Marriage"
  },
  {
    id: "p2-q2-20",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 2(a) & 2(b)",
    marks: 14,
    questionText: "(a) Explain two functions the family performs to benefit its members. [8]\n(b) Explain two strengths of functionalist views of the family. [6]",
    topic: "Theories of the Family",
    subTopic: "Stabilisation of Adult Personalities"
  },

  // =========================================================
  // PAPER 2: SECTION A - Question 3(a) & 3(b) (10 + 6 Marks)
  // =========================================================
  {
    id: "p2-q3-1",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "'Marriage has become less important in society.'\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Family Diversity & Social Change",
    subTopic: "Individualisation & Value of Marriage"
  },
  {
    id: "p2-q3-2",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "'Conjugal roles have become equal.'\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Gender Roles and Relationships",
    subTopic: "Symmetrical Family vs Triple Shift"
  },
  {
    id: "p2-q3-3",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "'Cohabitation is replacing marriage.'\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Family Diversity & Social Change",
    subTopic: "Cohabitation vs Trial Marriage"
  },
  {
    id: "p2-q3-4",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "'Social class is the main influence on family structure.'\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Family Diversity & Social Change",
    subTopic: "Organisational & Class Diversity (Rapoports)"
  },
  {
    id: "p2-q3-5",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "'The main role of the family is to serve the needs of capitalism.'\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Theories of the Family",
    subTopic: "Marxist Perspectives & Zaretsky"
  },
  {
    id: "p2-q3-6",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "'Changes in social policy are the main reason for an increase in divorce.'\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Family Diversity & Social Change",
    subTopic: "Divorce Reform Acts & Secularisation"
  },
  {
    id: "p2-q3-7",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "'The experience of childhood is different today than in the past.'\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Childhood and Age",
    subTopic: "Aries, Historical Childhood & Toxic Childhood"
  },
  {
    id: "p2-q3-8",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "'Men have more power than women in the family.'\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Gender Roles and Relationships",
    subTopic: "Financial Decision Making (Pahl & Vogler) & Domestic Violence"
  },
  {
    id: "p2-q3-9",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "'Men continue to dominate family life.'\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Gender Roles and Relationships",
    subTopic: "Patriarchy & Conjugal Division"
  },
  {
    id: "p2-q3-10",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "'The nuclear family is the dominant family structure.'\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Family Diversity & Social Change",
    subTopic: "Chester (Neo-Conventional) vs Rapoports Diversity"
  },
  {
    id: "p2-q3-11",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "'The family has experienced a loss of functions.'\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Theories of the Family",
    subTopic: "Structural Differentiation & Loss of Functions (Parsons)"
  },
  {
    id: "p2-q3-12",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "'The improved social position of women is the main reason for the increase in divorce.'\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Family Diversity & Social Change",
    subTopic: "Female Financial Independence & Divorce"
  },
  {
    id: "p2-q3-13",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "'Women continue to perform the majority of tasks in the family.'\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Gender Roles and Relationships",
    subTopic: "Dual Burden & Triple Shift (Duncombe & Marsden)"
  },
  {
    id: "p2-q3-14",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "'Childhood as a distinct period of life is disappearing today.'\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Childhood and Age",
    subTopic: "Postman (Disappearance of Childhood) vs Palmer"
  },
  {
    id: "p2-q3-15",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "'The extent of family diversity has been exaggerated.'\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Family Diversity & Social Change",
    subTopic: "Chester Neo-Conventional Family vs Postmodernism"
  },
  {
    id: "p2-q3-16",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "'Grandparents make a positive contribution to family life.'\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Childhood and Age",
    subTopic: "Beanpole Families & Informal Childcare"
  },
  {
    id: "p2-q3-17",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "'The main reason for family diversity is changes in social policy.'\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Family Diversity & Social Change",
    subTopic: "Social Policy, Divorce Act & Cultural Shifts"
  },
  {
    id: "p2-q3-18",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "'Social class is the most important factor affecting the experiences of children in the family.'\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Childhood and Age",
    subTopic: "Childhood Inequalities & Class Stratification"
  },
  {
    id: "p2-q3-19",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "'The main role of the family is to benefit society.'\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Theories of the Family",
    subTopic: "Functionalism vs Marxism/Feminism"
  },
  {
    id: "p2-q3-20",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section A",
    questionNumber: "Question 3(a) & 3(b)",
    marks: 16,
    questionText: "'There is no longer any social pressure on people to get married.'\n(a) Explain this view. [10]\n(b) Using sociological material, give one argument against this view. [6]",
    topic: "Family Diversity & Social Change",
    subTopic: "Secularisation, Pure Relationships & Marriage Norms"
  },

  // =========================================================
  // PAPER 2: SECTION B - Essays (26 Marks)
  // =========================================================
  {
    id: "p2-secb-1",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that family life is harmful for some family members. [26]",
    topic: "Theories of the Family",
    subTopic: "Dark Side of the Family, Radical Feminism & Leach/Laing"
  },
  {
    id: "p2-secb-2",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that cultural differences are the main reason for family diversity. [26]",
    topic: "Family Diversity & Social Change",
    subTopic: "Cultural Diversity vs Class and Cohort Diversity"
  },
  {
    id: "p2-secb-3",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that the family has lost many of its functions. [26]",
    topic: "Theories of the Family",
    subTopic: "Loss of Functions & Structural Differentiation (Parsons vs Fletcher)"
  },
  {
    id: "p2-secb-4",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that in contemporary society the family has become child-centred. [26]",
    topic: "Childhood and Age",
    subTopic: "Child-Centredness vs Toxic Childhood & Inequalities"
  },
  {
    id: "p2-secb-5",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the functionalist perspective on the role of the family. [26]",
    topic: "Theories of the Family",
    subTopic: "Functionalism (Murdock & Parsons) vs Critical Perspectives"
  },
  {
    id: "p2-secb-6",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that social policies have had a positive impact upon the family. [26]",
    topic: "Family Diversity & Social Change",
    subTopic: "Social Policy, Functionalism, New Right & Feminism"
  },
  {
    id: "p2-secb-7",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that increased social opportunities for women are the main reason for the rise in divorce rates. [26]",
    topic: "Family Diversity & Social Change",
    subTopic: "Changing Female Opportunities vs Legal and Secular Shifts"
  },
  {
    id: "p2-secb-8",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate Marxist explanations of the role of the family. [26]",
    topic: "Theories of the Family",
    subTopic: "Marxism, Engels, Zaretsky & Ideological Reproduction"
  },
  {
    id: "p2-secb-9",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that conjugal roles are equally shared between men and women today. [26]",
    topic: "Gender Roles and Relationships",
    subTopic: "Symmetrical Family vs Triple Shift & Domestic Labour"
  },
  {
    id: "p2-secb-10",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that the nuclear family continues to be the dominant family structure. [26]",
    topic: "Family Diversity & Social Change",
    subTopic: "Chester Neo-Conventional vs Postmodern Diversity"
  },
  {
    id: "p2-secb-11",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that roles in the family are no longer fixed. [26]",
    topic: "Gender Roles and Relationships",
    subTopic: "Individualisation, Pure Relationships & Gender Flexibility"
  },
  {
    id: "p2-secb-12",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that the family benefits all its members equally. [26]",
    topic: "Theories of the Family",
    subTopic: "Consensus Theory vs Feminist Patriarchy & Marxist Exploitation"
  },
  {
    id: "p2-secb-13",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that social policies are the main reason for increased family diversity. [26]",
    topic: "Family Diversity & Social Change",
    subTopic: "Social Policies vs Economic and Cultural Factors"
  },
  {
    id: "p2-secb-14",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that the family is a patriarchal institution. [26]",
    topic: "Theories of the Family",
    subTopic: "Feminist Theories of Patriarchy vs March of Progress"
  },
  {
    id: "p2-secb-15",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that increased life expectancy has had a positive impact on family members. [26]",
    topic: "Childhood and Age",
    subTopic: "Demography, Beanpole Families & Care Burdens"
  },
  {
    id: "p2-secb-16",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that the nuclear family is no longer the dominant family form. [26]",
    topic: "Family Diversity & Social Change",
    subTopic: "Nuclear Family Decline vs Chester Life-Cycle Continuity"
  },
  {
    id: "p2-secb-17",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that motherhood is different today than in the past. [26]",
    topic: "Gender Roles and Relationships",
    subTopic: "Motherhood, Employment, Intensive Mothering & Childcare"
  },
  {
    id: "p2-secb-18",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that the main role of the family is to promote social stability. [26]",
    topic: "Theories of the Family",
    subTopic: "Functionalism, Social Order vs Conflict Theories"
  },
  {
    id: "p2-secb-19",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that grandparents play a positive role in the family. [26]",
    topic: "Childhood and Age",
    subTopic: "Grandparenting, Extended Families & Emotional/Economic Support"
  },
  {
    id: "p2-secb-20",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that the main role of the family is to serve the needs of capitalism. [26]",
    topic: "Theories of the Family",
    subTopic: "Marxism, Unit of Consumption & Ideological Conditioning"
  },
  {
    id: "p2-secb-21",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that social class is the main factor affecting the experiences of children in the family. [26]",
    topic: "Childhood and Age",
    subTopic: "Childhood Stratification, Cultural/Economic Capital & Class"
  },
  {
    id: "p2-secb-22",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that increasing family diversity means the nuclear family is no longer dominant. [26]",
    topic: "Family Diversity & Social Change",
    subTopic: "Postmodern Diversity vs Neo-Conventional Nuclear Family"
  },
  {
    id: "p2-secb-23",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that gender no longer influences roles within the family. [26]",
    topic: "Gender Roles and Relationships",
    subTopic: "Egalitarian Roles vs Persistent Gendered Division of Labour"
  },
  {
    id: "p2-secb-24",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that childhood is a period of innocence and protection. [26]",
    topic: "Childhood and Age",
    subTopic: "Western Notion of Childhood vs Abuse, Exploitation & Inequality"
  },
  {
    id: "p2-secb-25",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that cultural factors are the main influence on family structure. [26]",
    topic: "Family Diversity & Social Change",
    subTopic: "Cultural and Ethnic Diversity vs Economic Forces"
  },
  {
    id: "p2-secb-26",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that the main role of the family is to serve ruling class interests. [26]",
    topic: "Theories of the Family",
    subTopic: "Marxism, Ruling Class Ideology vs Functional Needs"
  },
  {
    id: "p2-secb-27",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that gender is the most important factor influencing family life. [26]",
    topic: "Gender Roles and Relationships",
    subTopic: "Gender Divisions vs Class, Ethnicity and Age"
  },
  {
    id: "p2-secb-28",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that family structure is now characterised by diversity. [26]",
    topic: "Family Diversity & Social Change",
    subTopic: "Rapoport & Rapoport 5 Types of Diversity vs Chester"
  },
  {
    id: "p2-secb-29",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that women's changing expectations of marriage is the main reason for the increase in divorce. [26]",
    topic: "Family Diversity & Social Change",
    subTopic: "Confluent Love, Expectations & Divorce Rates"
  },
  {
    id: "p2-secb-30",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that Marxist explanations offer the best understanding of the role of the family. [26]",
    topic: "Theories of the Family",
    subTopic: "Marxism vs Functionalism, Feminism and Personal Life"
  },
  {
    id: "p2-secb-31",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that the main role of the family is to reproduce inequality in society. [26]",
    topic: "Theories of the Family",
    subTopic: "Reproduction of Class and Gender Inequality"
  },
  {
    id: "p2-secb-32",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that gender is the main influence on a child's experience of family life. [26]",
    topic: "Childhood and Age",
    subTopic: "Gender Socialisation (Oakley) vs Class and Ethnicity"
  },
  {
    id: "p2-secb-33",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that marriage is no longer socially important. [26]",
    topic: "Family Diversity & Social Change",
    subTopic: "Decline of Marriage, Remarriage & Cohabitation"
  },
  {
    id: "p2-secb-34",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that there is greater gender equality in the family today. [26]",
    topic: "Gender Roles and Relationships",
    subTopic: "March of Progress vs Feminist Perspectives on Inequality"
  },
  {
    id: "p2-secb-35",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that the main role of the family is to promote capitalist ideology. [26]",
    topic: "Theories of the Family",
    subTopic: "Althusser, Zaretsky & Ideological Functions"
  },
  {
    id: "p2-secb-36",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that marriage has become less important in society. [26]",
    topic: "Family Diversity & Social Change",
    subTopic: "Changing Significance of Marriage vs Ongoing Popularity"
  },
  {
    id: "p2-secb-37",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that roles in the family are still based on traditional gender identities. [26]",
    topic: "Gender Roles and Relationships",
    subTopic: "Traditional Segregated vs Symmetrical Conjugal Roles"
  },
  {
    id: "p2-secb-38",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that the nuclear family is the dominant family type. [26]",
    topic: "Family Diversity & Social Change",
    subTopic: "Dominance of the Nuclear Family vs Complex Diversity"
  },
  {
    id: "p2-secb-39",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that cultural differences are the main cause of family diversity. [26]",
    topic: "Family Diversity & Social Change",
    subTopic: "Cultural Pluralism vs Socio-Economic Drivers of Diversity"
  },
  {
    id: "p2-secb-40",
    paper: "Paper 2",
    paperTitle: "Paper 2: The Family",
    section: "Section B",
    questionNumber: "Essay (26m)",
    marks: 26,
    questionText: "Evaluate the view that parenthood today is different from the past. [26]",
    topic: "Gender Roles and Relationships",
    subTopic: "Changing Parenting, Intensive Parenting & Co-Parenting"
  }
];
